name: Runner Deploy actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies token
      uses: cschleiden/replace-tokens@v1
      with:
       tokenPrefix: '#{'
       tokenSuffix: '}#'
       files: 'Dockerfile'   
      env:
       GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
       GITHUB_USER: ${{secrets.GH_USER}}
       GITHUB_REPOSITORY : ${{secrets.GH_REPOSITORY}}
       GITHUB_VERSION: 2.285.1
        
        
    - name: Build the Docker image push DOCKER HUB
      env:
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        USER: ${{secrets.DOCKER_USER}}
        TOKEN : ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $USER --password $TOKEN
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TA
        
    
